name = "Meme 5 Server"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "56d3e9baf3e7035d25515c4954e6524208541cd5551bdfeb54a69a947800a596"

[versions]
fabric = "0.14.8"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1", "1.19.2"]
