name = "Meme 5 Server"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb2ad9b9a90b209651e5fb48f0c4d35e1c84843ff57725eeeb2b97f926b3d703"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
