name = "Meme 5 Server"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11fbd23ad5ebbb764300803fe5410443835995acd93dd7663bb5ef20d5d92a27"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
