name = "Meme 5 Server"
author = "Fauli1221"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9a84bc11a62a6d4ecdf1f3e488bcf99f917548f1a5a76e18943c5f8554f2f28"

[versions]
fabric = "0.14.9"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19.1", "1.19.2"]
