name = "Meme 5 Server"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bcaedda70667001ac42619ed9e4215e26bf88664b95d2f5cad41438788a7669"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
