name = "Meme 5 Server"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df37bf2ebed3f8baa9581599be289489b411986eaf72571f896964ddc1595ec4"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
