name = "Meme 5 Server"
author = "Fauli1221"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f1f589d4705bf702587d0bb7182eb232d0b4b61960cc32cc6fd9d3abeb83c85"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
