name = "Big Pony"
filename = "bigpony-1.7.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/h9pJxJR9/versions/1.7.0/bigpony-1.7.0.jar"
hash-format = "sha1"
hash = "2b0532b5918c3ebe397d32cec4fbfcaa9e16ff11"

[update]
[update.modrinth]
mod-id = "h9pJxJR9"
version = "WYY5uUB7"
