name = "Chunky Pregenerator (Fabric)"
filename = "Chunky-1.2.202.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "36d0f84689e642431b3233b93bb26dfe44f716b4"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3822136
project-id = 433175
