name = "Debugify"
filename = "debugify-fabric-1.6.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/QwxR6Gcd/versions/1.6.0-fabric/debugify-fabric-1.6.0.jar"
hash-format = "sha1"
hash = "2b22fbe03f8478e3a0376aef58e0f9fb0f65f41e"

[update]
[update.modrinth]
mod-id = "QwxR6Gcd"
version = "J3zRK5bi"
