name = "EditSign (Forge&Fabric)"
filename = "EditSign-1.19.1-2.5.0.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "ca14f9b9cbac4df768756c967bce2acc1323373c"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3902632
project-id = 344996
