name = "EditSign (Forge&Fabric)"
filename = "EditSign-1.19-2.4.0.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "4665a6e408978e43ae9ef2659469cc766e725c40"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3821089
project-id = 344996
