name = "Essential Commands"
filename = "essential_commands-0.22.0-mc1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/6VdDUivB/versions/0.22.0-mc1.18.2/essential_commands-0.22.0-mc1.18.2.jar"
hash-format = "sha1"
hash = "16cbc14a8ed235d8efda5e777cdca3e73b9a8dc8"

[update]
[update.modrinth]
mod-id = "6VdDUivB"
version = "Bi42Q9uj"
