name = "Essential Commands"
filename = "essential_commands-0.24.0-beta-mc1.19-dev.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/6VdDUivB/versions/0.24.0-beta-mc1.19/essential_commands-0.24.0-beta-mc1.19-dev.jar"
hash-format = "sha1"
hash = "71641ef048c0c3416fce97468fe6d5ed70f9d7a9"

[update]
[update.modrinth]
mod-id = "6VdDUivB"
version = "MWFWNh6i"
