name = "Fabric API"
filename = "fabric-api-0.53.3+1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "5ae8fbf0d452bf2caab0342797687f60dfe99a37"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3802464
project-id = 306612
