name = "FallingTree"
filename = "FallingTree-1.19.1-3.8.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Fb4jn8m6/versions/1.19.1-3.8.0/FallingTree-1.19.1-3.8.0.jar"
hash-format = "sha1"
hash = "dc81fc3a9ef16671769f3ae527838507f5dd1580"

[update]
[update.modrinth]
mod-id = "Fb4jn8m6"
version = "bQrEMzOP"
