name = "FallingTree"
filename = "FallingTree-1.19-3.6.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Fb4jn8m6/versions/1.19-3.6.0/FallingTree-1.19-3.6.0.jar"
hash-format = "sha1"
hash = "bf38bcf2a388e7a51445149ba7d598bbf33b2a78"

[update]
[update.modrinth]
mod-id = "Fb4jn8m6"
version = "zv2J7DYl"
