name = "Flan"
filename = "flan-1.18.2-1.7.6-fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3737/464/flan-1.18.2-1.7.6-fabric.jar"
hash-format = "sha1"
hash = "f53127ba8c31864db8bc88315847059300be996a"

[update]
[update.curseforge]
file-id = 3737464
project-id = 404578
