name = "Flan"
filename = "flan-1.18.2-1.7.8-fabric.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "08e77693484f54385b2081c3862c21fdc21ac5f5"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3793954
project-id = 404578
