name = "GolfIV"
filename = "golfiv-0.5.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/PfKYAJGk/versions/0.5.1/golfiv-0.5.1.jar"
hash-format = "sha1"
hash = "add8db0fc5c9ec3893ff414754e0cce8a80e7fc0"

[update]
[update.modrinth]
mod-id = "PfKYAJGk"
version = "dtIYL2j7"
