name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.2-2.2.39.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/fabric-1.18.2-2.2.39/voicechat-fabric-1.18.2-2.2.39.jar"
hash-format = "sha1"
hash = "6a1661d4617c04fd9df02c81a72095dc27fd4383"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "yS8N6ZXU"
