name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.2-2.2.37.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/fabric-1.18.2-2.2.37/voicechat-fabric-1.18.2-2.2.37.jar"
hash-format = "sha1"
hash = "1b45cc8fba28a2c9ac7f06504d5e3d50d4ebc0f3"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "jzGURoFS"
