name = "Simple Voice Chat"
filename = "voicechat-fabric-1.19.2-2.3.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/fabric-1.19.2-2.3.2/voicechat-fabric-1.19.2-2.3.2.jar"
hash-format = "sha1"
hash = "bd7a17b94db3e45acc3ea139fe8dd10d9360ca15"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "UuVA043m"
