name = "Simple Voice Chat"
filename = "voicechat-fabric-1.19-2.2.51.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/fabric-1.19-2.2.51/voicechat-fabric-1.19-2.2.51.jar"
hash-format = "sha1"
hash = "db5e49f00d2fad030fac581c63b15e122a7ee328"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "skCygDOW"
