name = "Simple Voice Chat"
filename = "voicechat-fabric-1.19-2.3.5.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/fabric-1.19-2.3.5/voicechat-fabric-1.19-2.3.5.jar"
hash-format = "sha1"
hash = "6cef019173976e8fef39c5403dcf1a6e7e7dcd44"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "b8NlnipH"
