name = "Simple Voice Chat"
filename = "voicechat-quilt-1.19.1-2.3.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/quilt-1.19.1-2.3.1/voicechat-quilt-1.19.1-2.3.1.jar"
hash-format = "sha1"
hash = "1775fb169887935b308d7766721f149871a3febe"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "DKEL9dyW"
