name = "Simple Voice Chat"
filename = "voicechat-quilt-1.19.1-2.2.52.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/9eGKb6K1/versions/quilt-1.19.1-2.2.52/voicechat-quilt-1.19.1-2.2.52.jar"
hash-format = "sha1"
hash = "cd7d901bd9dae53b63c917ae52f55e5ffcbc7fd3"

[update]
[update.modrinth]
mod-id = "9eGKb6K1"
version = "qwotpGek"
