name = "ViaFabric"
filename = "viafabric-0.4.6+271-main.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3764/678/viafabric-0.4.6+271-main.jar"
hash-format = "sha1"
hash = "f10638b619321b0ea3a382ef7792fecb88dbb5c3"

[update]
[update.curseforge]
file-id = 3764678
project-id = 391298
