name = "ViaFabric"
filename = "viafabric-0.4.7+1-main.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "8a514893b2e43b32234f359c58a6ace2f56b7def"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3801629
project-id = 391298
