name = "ViaFabric"
filename = "viafabric-0.4.7+5-main.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "c5de725a5403222cf97e5a222431a9702cf96313"
mode = "metadata:curseforge"

[update]
[update.curseforge]
file-id = 3820900
project-id = 391298
